# Generated by Django 6.1.1 on 2026-10-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=10)),
                ('Brand', models.CharField(max_length=10)),
                ('Colour', models.CharField(max_length=10)),
                ('Year', models.IntegerField()),
                ('Price', models.DecimalField()),
                ('Model_name', models.CharField(max_length=10)),
            ],
        ),
    ]
